on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
    - name: Bump versions
      uses: remorses/bump-version@js
      with:
        version_file: ./internal/config/config.go
        prerelease_tag: alpha
        github_token: ${{ secrets.GITHUB_TOKEN }}
