name: Version Bump

on:
  push:
    branches:
      - master

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Version bump
        uses: remorses/bump-version@js
        with:
            version_file: ./VERSION
            github_token: ${{ secrets.GITHUB_TOKEN }}
            prerelease_tag: alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
